---
- name: Deny everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: SSH Access
  community.general.ufw:    
    rule: limit
    port: ssh
    proto: tcp
    src: "{{ local_network.cidr }}"

- name: HTTP
  community.general.ufw:    
    rule: allow
    port: 80
    proto: tcp
    src: "{{ local_network.cidr }}"
    comment: "http"

- name: HTTPS
  community.general.ufw:    
    rule: allow
    port: 443
    proto: tcp
    src: "{{ local_network.cidr }}"
    comment: "Https"

- name: PostgreSQL
  community.general.ufw:    
    rule: allow
    port: 5432
    proto: tcp
    src: "{{ local_network.cidr }}"
    comment: "Postgres"