---
- name: Download k3s binary for arm64 nodes
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s.version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s.version }}/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  register: binary_downloaded

- block:
    - name: Populate service facts
      service_facts:

    - name: Restart service k3s if binary was downloaded
      service:
        name: k3s
        state: restarted
        enabled: yes
      when: "'k3s' in services"

  when: binary_downloaded.changed == true
