---
- name: Set timezone to America/Sao_Paulo
  community.general.timezone:
    name: America/Sao_Paulo

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"

###
### K8s e K3s requirements
###
- name: Install vxlan support
  apt:
    name: linux-modules-extra-raspi
    update_cache: true
    state: present
  when: ansible_distribution == 'Ubuntu'
# TODO: Check if this is needed on Debian

- name: Disable swap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  notify: os_reboot

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- set_fact:
    cmdline: "/boot/firmware/cmdline.txt"
  when: ansible_distribution == 'Ubuntu'

- set_fact:
    cmdline: "/boot/cmdline.txt"
  when: ansible_distribution == 'Debian'

- name: Enable cgroup params on boot for {{ ansible_distribution }}
  replace:
    path: "{{ cmdline }}"
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  notify: os_reboot
