all:
  children:
    raspberrys:
      children:
        server:
          hosts:
            192.168.0.11:
              hostname: k3s-11s
        agents:
          hosts:
            192.168.0.12:
              hostname: k3s-12c
              #ansible_user: ubuntu
            192.168.0.13:
              hostname: k3s-13c
            192.168.0.14:
              hostname: k3s-14c
            192.168.0.15:
              hostname: k3s-15c
            192.168.0.16:
              hostname: k3s-16c
