all:  
  children:
    raspberrys:
      children:
        fourGb:      
          hosts:
            192.168.0.21:            
              hostname: k3s-01
        twoGb:      
          hosts:
            192.168.0.22:
              hostname: k3s-02
            192.168.0.23:
              hostname: k3s-03
    