all:  
  children:
    raspberrys:
      children:
        server:      
          hosts:
            192.168.0.21:            
              hostname: alfa
        agents:      
          hosts:
            192.168.0.22:
              hostname: beta
            192.168.0.23:
              hostname: charlie
    