all:
  children:
    raspberrys:
      children:
        server:
          hosts:
            192.168.0.11:
              hostname: k3s-11s
        agents:
          hosts:
            192.168.0.12:
              hostname: k3s-12c
            192.168.0.13:
              hostname: k3s-13c
