all:
  children:
    raspberrys:
      children:
        fourGb:
          hosts:
            192.168.0.13:
              hostname: k3s-13
        twoGb:
          hosts:
            192.168.0.11:
              hostname: k3s-11
            192.168.0.12:
              hostname: k3s-12
