- hosts: raspberrys
  user: ubuntu
  become: true
  gather_facts: false
  handlers:  
    - name: Reboot
      reboot:
        msg: "Reboot initiated by Ansible after cloud-init changed"
      listen: os_reboot    
  roles: 
    - { role: os, tags: ["os"] }

- hosts: server
  user: ubuntu
  become: true
  gather_facts: false
  handlers:    
  roles:
    - { role: k3s_server, tags: ["k3s", "server"] }
    - { role: nfs_server, tags: ["nfs", "server"] }
    - { role: nfs_client, tags: ["nfs", "client"] } 

- hosts: agents
  user: ubuntu
  become: true
  gather_facts: false    
  roles:
    - { role: k3s_agent, tags: ["k3s", "client"] }  
    - { role: nfs_client, tags: ["nfs", "client"] }  
